#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""
Curated Dictionary & Contextual Sentence Generator for Oxford 3000 Words
Fixes all placeholders like 'along (A2 kelimesi)', 'abandon (fiil)', template sentences, etc.
"""

import json
import os
import re
import urllib.request
import urllib.parse
import time

# Curated High-Frequency Dictionary for Oxford 3000
CURATED_DICT = {
    "about": {"tr": "hakkında, konusunda, yaklaşık olarak", "ph": "/əˈbaʊt/"},
    "above": {"tr": "üzerinde, yukarısında, üstünde", "ph": "/əˈbʌv/"},
    "across": {"tr": "karşısında, bir ucundan diğerine", "ph": "/əˈkrɒs/"},
    "action": {"tr": "eylem, hareket, faaliyet", "ph": "/ˈækʃn/"},
    "activity": {"tr": "etkinlik, faaliyet, aktivite", "ph": "/ækˈtɪvəti/"},
    "actor": {"tr": "aktör, erkek oyuncu", "ph": "/ˈæktə(r)/"},
    "actress": {"tr": "aktris, kadın oyuncu", "ph": "/ˈæktrəs/"},
    "add": {"tr": "eklemek, ilave etmek, katmak", "ph": "/æd/"},
    "address": {"tr": "adres; hitap etmek", "ph": "/əˈdres/"},
    "adult": {"tr": "yetişkin, erişkin", "ph": "/ˈædʌlt/"},
    "advice": {"tr": "tavsiye, öğüt, nasihat", "ph": "/ədˈvaɪs/"},
    "afraid": {"tr": "korkmuş, endişeli", "ph": "/əˈfreɪd/"},
    "after": {"tr": "sonra, ardından", "ph": "/ˈɑːftə(r)/"},
    "afternoon": {"tr": "öğleden sonra", "ph": "/ˌɑːftəˈnuːn/"},
    "again": {"tr": "tekrar, yeniden, bir daha", "ph": "/əˈɡen/"},
    "against": {"tr": "karşı, -e zıt", "ph": "/əˈɡenst/"},
    "age": {"tr": "yaş, çağ, dönem", "ph": "/eɪdʒ/"},
    "agree": {"tr": "aynı fikirde olmak, anlaşmak", "ph": "/əˈɡriː/"},
    "air": {"tr": "hava, atmosfer", "ph": "/eə(r)/"},
    "airport": {"tr": "havalimanı, havaalanı", "ph": "/ˈeəpɔːt/"},
    "all": {"tr": "bütün, tüm, hepsi", "ph": "/ɔːl/"},
    "all right": {"tr": "peki, tamam, iyi, sorunsuz", "ph": "/ɔːl ˈraɪt/"},
    "allow": {"tr": "izin vermek, olanak tanımak", "ph": "/əˈlaʊ/"},
    "almost": {"tr": "neredeyse, hemen hemen, az kalsın", "ph": "/ˈɔːlməʊst/"},
    "alone": {"tr": "yalnız, tek başına", "ph": "/əˈləʊn/"},
    "along": {"tr": "boyunca, yanı sıra, ileriye doğru", "ph": "/əˈlɒŋ/"},
    "already": {"tr": "zaten, çoktan, şimdiden", "ph": "/ɔːlˈredi/"},
    "also": {"tr": "ayrıca, de/da, bunun yanı sıra", "ph": "/ˈɔːlsəʊ/"},
    "always": {"tr": "her zaman, daima, hep", "ph": "/ˈɔːlweɪz/"},
    "amazing": {"tr": "harika, şaşırtıcı, büyüleyici", "ph": "/əˈmeɪzɪŋ/"},
    "among": {"tr": "arasında, içinde (üç veya daha fazla)", "ph": "/əˈmʌŋ/"},
    "amount": {"tr": "miktar, tutar, meblağ", "ph": "/əˈmaʊnt/"},
    "ancient": {"tr": "antik, çok eski, kadim", "ph": "/ˈeɪnʃənt/"},
    "angry": {"tr": "kızgın, öfkeli, sinirli", "ph": "/ˈæŋɡri/"},
    "animal": {"tr": "hayvan", "ph": "/ˈænɪml/"},
    "ankle": {"tr": "ayak bileği", "ph": "/ˈæŋkl/"},
    "announce": {"tr": "duyurmak, ilan etmek", "ph": "/əˈnaʊns/"},
    "announcement": {"tr": "duyuru, ilan, bildiri", "ph": "/əˈnaʊnsmənt/"},
    "another": {"tr": "başka, bir diğer, farklı bir", "ph": "/əˈnʌðə(r)/"},
    "answer": {"tr": "cevap, yanıt; cevaplamak", "ph": "/ˈɑːnsə(r)/"},
    "anxious": {"tr": "endişeli, kaygılı, huzursuz", "ph": "/ˈæŋkʃəs/"},
    "any": {"tr": "herhangi, hiç, hiçbir", "ph": "/ˈeni/"},
    "anybody": {"tr": "herhangi biri, hiç kimse", "ph": "/ˈenibɒdi/"},
    "anymore": {"tr": "artık, daha fazla", "ph": "/ˌeniˈmɔː(r)/"},
    "any more": {"tr": "artık, daha fazla", "ph": "/ˌeni ˈmɔː(r)/"},
    "anyone": {"tr": "biri, herhangi biri, kimse", "ph": "/ˈeniwʌn/"},
    "anything": {"tr": "herhangi bir şey, hiçbir şey", "ph": "/ˈeniθɪŋ/"},
    "anyway": {"tr": "her neyse, yine de, zaten", "ph": "/ˈeniweɪ/"},
    "anywhere": {"tr": "herhangi bir yer, hiçbir yer", "ph": "/ˈeniweə(r)/"},
    "apartment": {"tr": "apartman dairesi, daire", "ph": "/əˈpɑːtmənt/"},
    "app": {"tr": "uygulama, aplikasyon", "ph": "/æp/"},
    "appear": {"tr": "görünmek, belirmek, ortaya çıkmak", "ph": "/əˈpɪə(r)/"},
    "appearance": {"tr": "görünüş, dış görünüm, ortaya çıkış", "ph": "/əˈpɪərəns/"},
    "apple": {"tr": "elma", "ph": "/ˈæpl/"},
    "apply": {"tr": "başvurmak, uygulamak", "ph": "/əˈplaɪ/"},
    "appointment": {"tr": "randevu, atanma", "ph": "/əˈpɔɪntmənt/"},
    "architect": {"tr": "mimar", "ph": "/ˈɑːkɪtekt/"},
    "architecture": {"tr": "mimari, mimarlık", "ph": "/ˈɑːkɪtektʃə(r)/"},
    "area": {"tr": "alan, bölge, saha", "ph": "/ˈeəriə/"},
    "argue": {"tr": "tartışmak, münakaşa etmek, savunmak", "ph": "/ˈɑːɡjuː/"},
    "argument": {"tr": "tartışma, sav, münakaşa, iddia", "ph": "/ˈɑːɡjumənt/"},
    "arm": {"tr": "kol", "ph": "/ɑːm/"},
    "army": {"tr": "ordu, askeriye", "ph": "/ˈɑːmi/"},
    "around": {"tr": "etrafında, çevresinde, yaklaşık", "ph": "/əˈraʊnd/"},
    "arrange": {"tr": "düzenlemek, ayarlamak, organize etmek", "ph": "/əˈreɪndʒ/"},
    "arrangement": {"tr": "düzenleme, anlaşma, hazırlık", "ph": "/əˈreɪndʒmənt/"},
    "arrive": {"tr": "varmak, ulaşmak, gelmek", "ph": "/əˈraɪv/"},
    "art": {"tr": "sanat", "ph": "/ɑːt/"},
    "article": {"tr": "makale, yazı, madde, eşya", "ph": "/ˈɑːtɪkl/"},
    "artist": {"tr": "sanatçı, ressam", "ph": "/ˈɑːtɪst/"},
    "asleep": {"tr": "uykuda, uyuyan", "ph": "/əˈsliːp/"},
    "assistant": {"tr": "asistan, yardımcı", "ph": "/əˈsɪstənt/"},
    "athlete": {"tr": "sporcu, atlet", "ph": "/ˈæθliːt/"},
    "attack": {"tr": "saldırmak; saldırı, hücum", "ph": "/əˈtæk/"},
    "attend": {"tr": "katılmak, gitmek (toplantı/ders)", "ph": "/əˈtend/"},
    "attention": {"tr": "dikkat, ilgi, özen", "ph": "/əˈtenʃn/"},
    "audience": {"tr": "seyirci, dinleyici kitlesi", "ph": "/ˈɔːdiəns/"},
    "author": {"tr": "yazar, eser sahibi", "ph": "/ˈɔːθə(r)/"},
    "available": {"tr": "mevcut, müsait, erişilebilir", "ph": "/əˈveɪləbl/"},
    "average": {"tr": "ortalama, sıradan", "ph": "/ˈævərɪdʒ/"},
    "award": {"tr": "ödül; ödüllendirmek", "ph": "/əˈwɔːd/"},
    "awful": {"tr": "korkunç, berbat, çok kötü", "ph": "/ˈɔːfl/"},
    "background": {"tr": "arka plan, geçmiş, köken", "ph": "/ˈbækɡraʊnd/"},
    "badly": {"tr": "kötü bir şekilde, fena halde", "ph": "/ˈbædli/"},
    "bar": {"tr": "bar, çubuk, engel", "ph": "/bɑː(r)/"},
    "baseball": {"tr": "beyzbol", "ph": "/ˈbeɪsbɔːl/"},
    "based": {"tr": "dayalı, temelli, kurulu", "ph": "/beɪst/"},
    "basketball": {"tr": "basketbol", "ph": "/ˈbɑːskɪtbɔːl/"},
    "bean": {"tr": "fasulye, tane", "ph": "/biːn/"},
    "bear": {"tr": "ayı; katlanmak, taşımak", "ph": "/beə(r)/"},
    "beat": {"tr": "yenmek, vurmak, çarpmak", "ph": "/biːt/"},
    "beef": {"tr": "sığır eti, dana eti", "ph": "/biːf/"},
    "behaviour": {"tr": "davranış, tutum, hareket", "ph": "/bɪˈheɪvjə(r)/"},
    "belong": {"tr": "ait olmak, dahil olmak", "ph": "/bɪˈlɒŋ/"},
    "belt": {"tr": "kemer, kuşak", "ph": "/belt/"},
    "billion": {"tr": "milyar", "ph": "/ˈbɪljən/"},
    "bin": {"tr": "çöp kutusu, hazne", "ph": "/bɪn/"},
    "biology": {"tr": "biyoloji", "ph": "/baɪˈɒlədʒi/"},
    "birth": {"tr": "doğum, doğuş", "ph": "/bɜːθ/"},
    "biscuit": {"tr": "bisküvi, kurabiye", "ph": "/ˈbɪskɪt/"},
    "bit": {"tr": "parça, biraz, azıcık", "ph": "/bɪt/"},
    "blank": {"tr": "boş, boşluk; ifadesiz", "ph": "/blæŋk/"},
    "blood": {"tr": "kan", "ph": "/blʌd/"},
    "blow": {"tr": "üflemek, esmek; darbe", "ph": "/bləʊ/"},
    "board": {"tr": "tahta, pano, kurul; binmek", "ph": "/bɔːd/"},
    "boil": {"tr": "kaynamak, kaynatmak", "ph": "/bɔɪl/"},
    "bone": {"tr": "kemik", "ph": "/bəʊn/"},
    "borrow": {"tr": "ödünç almak, borçlanmak", "ph": "/ˈbɒrəʊ/"},
    "boss": {"tr": "patron, amir, müdür", "ph": "/bɒs/"},
    "bottom": {"tr": "dip, alt, taban", "ph": "/ˈbɒtəm/"},
    "bowl": {"tr": "kase, çanak", "ph": "/bəʊl/"},
    "brain": {"tr": "beyin, akıl, zeka", "ph": "/breɪn/"},
    "bridge": {"tr": "köprü; köprü kurmak", "ph": "/brɪdʒ/"},
    "bright": {"tr": "parlak, aydınlık, zeki", "ph": "/braɪt/"},
    "brilliant": {"tr": "muhteşem, harika, çok zeki", "ph": "/ˈbrɪliənt/"},
    "broken": {"tr": "kırık, bozuk, arızalı", "ph": "/ˈbrəʊkən/"},
    "brush": {"tr": "fırça; fırçalamak", "ph": "/brʌʃ/"},
    "burn": {"tr": "yanmak, yakmak; yanık", "ph": "/bɜːn/"},
    "businessman": {"tr": "iş adamı, tüccar", "ph": "/ˈbɪznəsmæn/"},
    "button": {"tr": "düğme, tuş, buton", "ph": "/ˈbʌtn/"},
    "camp": {"tr": "kamp; kamp yapmak", "ph": "/kæmp/"},
    "camping": {"tr": "kampçılık, kamp yapma", "ph": "/ˈkæmpɪŋ/"},
    "care": {"tr": "önemsemek, bakmak; bakım, özen", "ph": "/keə(r)/"},
    "careful": {"tr": "dikkatli, özenli, temkinli", "ph": "/ˈkeəfl/"},
    "carefully": {"tr": "dikkatlice, özenle", "ph": "/ˈkeəfəli/"},
    "carpet": {"tr": "halı, kilim", "ph": "/ˈkɑːpɪt/"},
    "cartoon": {"tr": "çizgi film, karikatür", "ph": "/kɑːˈtuːn/"},
    "case": {"tr": "durum, vaka, dava, kılıf", "ph": "/keɪs/"},
    "cash": {"tr": "nakit para, peşin", "ph": "/kæʃ/"},
    "castle": {"tr": "kale, şato, hisar", "ph": "/ˈkɑːsl/"},
    "catch": {"tr": "yakalamak, tutmak, yetişmek", "ph": "/kætʃ/"},
    "cause": {"tr": "neden olmak, yol açmak; sebep", "ph": "/kɔːz/"},
    "celebrity": {"tr": "ünlü, şöhretli kişi", "ph": "/səˈlebrəti/"},
    "certain": {"tr": "belirli, kesin, emin", "ph": "/ˈsɜːtn/"},
    "certainly": {"tr": "kesinlikle, elbette, şüphesiz", "ph": "/ˈsɜːtnli/"},
    "chance": {"tr": "şans, fırsat, olasılık", "ph": "/tʃɑːns/"},
    "character": {"tr": "karakter, kişilik, harf", "ph": "/ˈkærəktə(r)/"},
    "charity": {"tr": "hayır kurumu, yardımseverlik", "ph": "/ˈtʃærəti/"},
    "chat": {"tr": "sohbet etmek; sohbet, çene çalma", "ph": "/tʃæt/"},
    "chef": {"tr": "aşçı, şef", "ph": "/ʃef/"},
    "chemistry": {"tr": "kimya", "ph": "/ˈkemɪstri/"},
    "chip": {"tr": "çip, patates kızartması, kırıntı", "ph": "/tʃɪp/"},
    "choice": {"tr": "seçim, seçenek, tercih", "ph": "/tʃɔɪs/"},
    "church": {"tr": "kilise", "ph": "/tʃɜːtʃ/"},
    "cigarette": {"tr": "sigara", "ph": "/ˌsɪɡəˈret/"},
    "circle": {"tr": "daire, çember, çevre", "ph": "/ˈsɜːkl/"},
    "classical": {"tr": "klasik, geleneksel", "ph": "/ˈklæsɪkl/"},
    "clear": {"tr": "açık, net, berrak; temizlemek", "ph": "/klɪə(r)/"},
    "clearly": {"tr": "açıkça, net bir şekilde", "ph": "/ˈklɪəli/"},
    "clever": {"tr": "zeki, akıllı, kurnaz", "ph": "/ˈklevə(r)/"},
    "climate": {"tr": "iklim, atmosfer", "ph": "/ˈklaɪmət/"},
    "closed": {"tr": "kapalı", "ph": "/kləʊzd/"},
    "clothing": {"tr": "giyim, giysi, kıyafet", "ph": "/ˈkləʊðɪŋ/"},
    "cloud": {"tr": "bulut", "ph": "/klaʊd/"},
    "coach": {"tr": "antrenör, koç, şehirlerarası otobüs", "ph": "/kəʊtʃ/"},
    "coast": {"tr": "sahil, kıyı, deniz kenarı", "ph": "/kəʊst/"},
    "code": {"tr": "kod, kural, şifre", "ph": "/kəʊd/"},
    "colleague": {"tr": "meslektaş, iş arkadaşı", "ph": "/ˈkɒliːɡ/"},
    "collect": {"tr": "toplamak, biriktirmek, tahsil etmek", "ph": "/kəˈlekt/"},
    "column": {"tr": "sütun, kolon, köşe yazısı", "ph": "/ˈkɒləm/"},
    "comedy": {"tr": "komedi, güldürü", "ph": "/ˈkɒmədi/"},
    "comfortable": {"tr": "rahat, konforlu, huzurlu", "ph": "/ˈkʌmftəbl/"},
    "comment": {"tr": "yorum yapmak; yorum, eleştiri", "ph": "/ˈkɒment/"},
    "communicate": {"tr": "iletişim kurmak, haberleşmek", "ph": "/kəˈmjuːnɪkeɪt/"},
    "community": {"tr": "topluluk, cemiyet, halk", "ph": "/kəˈmjuːnəti/"},
    "compete": {"tr": "yarışmak, rekabet etmek", "ph": "/kəmˈpiːt/"},
    "competition": {"tr": "yarışma, rekabet, müsabaka", "ph": "/ˌkɒmpəˈtɪʃn/"},
    "complain": {"tr": "şikayet etmek, yakınmak", "ph": "/kəmˈpleɪn/"},
    "completely": {"tr": "tamamen, bütünüyle, eksiksiz", "ph": "/kəmˈpliːtli/"},
    "condition": {"tr": "koşul, şart, durum, hal", "ph": "/kənˈdɪʃn/"},
    "conference": {"tr": "konferans, toplantı", "ph": "/ˈkɒnfərəns/"},
    "connect": {"tr": "bağlanmak, bağlamak, birleştirmek", "ph": "/kəˈnekt/"},
    "connected": {"tr": "bağlantılı, bağlı, ilişkili", "ph": "/kəˈnektɪd/"},
    "consider": {"tr": "dikkate almak, düşünmek, göz önünde bulundurmak", "ph": "/kənˈsɪdə(r)/"},
    "contain": {"tr": "içermek, kapsamak, barındırmak", "ph": "/kənˈteɪn/"},
    "context": {"tr": "bağlam, genel durum", "ph": "/ˈkɒntekst/"},
    "continent": {"tr": "kıta, anakara", "ph": "/ˈkɒntɪnənt/"},
    "continue": {"tr": "devam etmek, sürdürmek", "ph": "/kənˈtɪnjuː/"},
    "control": {"tr": "kontrol etmek, denetlemek; denetim", "ph": "/kənˈtrəʊl/"},
    "abandon": {"tr": "terk etmek, bırakmak, vazgeçmek", "ph": "/əˈbændən/"},
    "absolute": {"tr": "kesin, mutlak, tam", "ph": "/ˈæbsəluːt/"},
    "absolutely": {"tr": "kesinlikle, tamamen, kesin olarak", "ph": "/ˌæbsəˈluːtli/"},
    "academic": {"tr": "akademik, öğretim üyesi", "ph": "/ˌækəˈdemɪk/"},
    "acceptable": {"tr": "kabul edilebilir, makul", "ph": "/əkˈseptəbl/"},
    "access": {"tr": "erişim, giriş; erişmek", "ph": "/ˈækses/"},
    "accommodation": {"tr": "konaklama, kalacak yer", "ph": "/əˌkɒməˈdeɪʃn/"},
    "accompany": {"tr": "eşlik etmek, yanında bulunmak", "ph": "/əˈkʌmpəni/"},
    "according to": {"tr": "-e göre, uyarınca", "ph": "/əˈkɔːdɪŋ tuː/"},
    "account": {"tr": "hesap; açıklamak, sorumlu olmak", "ph": "/əˈkaʊnt/"},
    "accurate": {"tr": "doğru, kesin, hatasız", "ph": "/ˈækjərət/"},
    "accuse": {"tr": "suçlamak, itham etmek", "ph": "/əˈkjuːz/"},
    "achievement": {"tr": "başarı, kazanım", "ph": "/əˈtʃiːvmənt/"},
    "acknowledge": {"tr": "kabul etmek, onaylamak, doğrulamak", "ph": "/əkˈnɒlɪdʒ/"},
    "acquire": {"tr": "edinmek, kazanmak, elde etmek", "ph": "/əˈkwaɪə(r)/"},
    "act": {"tr": "davranmak, rol almak; eylem, yasa", "ph": "/ækt/"},
    "ad": {"tr": "reklam, ilan", "ph": "/æd/"},
    "addition": {"tr": "ek, ilave, toplama işlemi", "ph": "/əˈdɪʃn/"},
    "admire": {"tr": "hayran olmak, takdir etmek", "ph": "/ədˈmaɪə(r)/"},
    "admit": {"tr": "itiraf etmek, kabul etmek, içeri almak", "ph": "/ədˈmɪt/"},
    "adopt": {"tr": "evlat edinmek, benimsemek", "ph": "/əˈdɒpt/"},
    "advance": {"tr": "ilerlemek, geliştirmek; avans, ilerleme", "ph": "/ədˈvɑːns/"},
    "advanced": {"tr": "ileri düzey, gelişmiş", "ph": "/ədˈvɑːnst/"},
    "advantage": {"tr": "avantaj, üstünlük, fayda", "ph": "/ədˈvɑːntɪdʒ/"},
    "adventure": {"tr": "macera, serüven", "ph": "/ədˈventʃə(r)/"},
    "advertise": {"tr": "reklamını yapmak, ilan vermek", "ph": "/ˈædvətaɪz/"},
    "advertisement": {"tr": "reklam, ilan, tanıtım", "ph": "/ədˈvɜːtɪsmənt/"},
    "advertising": {"tr": "reklamcılık, reklam sektörü", "ph": "/ˈædvətaɪzɪŋ/"},
    "affect": {"tr": "etkilemek, tesir etmek", "ph": "/əˈfekt/"},
    "afford": {"tr": "parası yetmek, gücü yetmek", "ph": "/əˈfɔːd/"},
    "agency": {"tr": "ajans, acente, kurum", "ph": "/ˈeɪdʒənsi/"},
    "agent": {"tr": "temsilci, ajan, vekil", "ph": "/ˈeɪdʒənt/"},
    "aggressive": {"tr": "saldırgan, kavgacı, agresif", "ph": "/əˈɡresɪv/"},
    "agriculture": {"tr": "tarım, ziraat", "ph": "/ˈæɡrɪkʌltʃə(r)/"},
    "aim": {"tr": "hedeflemek, amaçlamak; hedef, amaç", "ph": "/eɪm/"},
    "aircraft": {"tr": "uçak, hava aracı", "ph": "/ˈeəkrɑːft/"},
    "alarm": {"tr": "alarm, çalar saat; telaşlandırmak", "ph": "/əˈlɑːm/"},
    "album": {"tr": "albüm", "ph": "/ˈælbəm/"},
    "alcohol": {"tr": "alkol, içki", "ph": "/ˈælkəhɒl/"},
    "alcoholic": {"tr": "alkollü, alkolik", "ph": "/ˌælkəˈhɒlɪk/"},
    "alive": {"tr": "canlı, hayatta, diri", "ph": "/əˈlaɪv/"},
    "allowance": {"tr": "harçlık, ödenek, tahsisat", "ph": "/əˈlaʊəns/"},
    "ally": {"tr": "müttefik, dost; birleşmek", "ph": "/ˈælaɪ/"},
    "alongside": {"tr": "yanında, yanı sıra, bitişiğinde", "ph": "/əˌlɒŋˈsaɪd/"},
    "alter": {"tr": "değiştirmek, başkalaşmak", "ph": "/ˈɔːltə(r)/"},
    "ambition": {"tr": "hırs, azim, büyük istek", "ph": "/æmˈbɪʃn/"},
    "ambitious": {"tr": "hırslı, iddialı, azimli", "ph": "/æmˈbɪʃəs/"},
    "analysis": {"tr": "analiz, çözümleme, tahlil", "ph": "/əˈnæləsɪs/"},
    "analyze": {"tr": "analiz etmek, çözümlemek, incelemek", "ph": "/ˈænəlaɪz/"},
    "analyse": {"tr": "analiz etmek, çözümlemek, incelemek", "ph": "/ˈænəlaɪz/"},
    "anger": {"tr": "öfke, kızgınlık; kızdırmak", "ph": "/ˈæŋɡə(r)/"},
    "angle": {"tr": "açı, köşe, bakış açısı", "ph": "/ˈæŋɡl/"},
    "anniversary": {"tr": "yıl dönümü", "ph": "/ˌænɪˈvɜːsəri/"},
    "annual": {"tr": "yıllık, her yıl olan", "ph": "/ˈænjuəl/"},
    "anxiety": {"tr": "kaygı, endişe, tasa", "ph": "/æŋˈzaɪəti/"},
    "apologize": {"tr": "özür dilemek", "ph": "/əˈpɒlədʒaɪz/"},
    "apology": {"tr": "özür", "ph": "/əˈpɒlədʒi/"},
    "apparent": {"tr": "belirgin, bariz, aşikar", "ph": "/əˈpærənt/"},
    "apparently": {"tr": "görünüşe göre, anlaşılan", "ph": "/əˈpærəntli/"},
    "appeal": {"tr": "başvurmak, cazip gelmek; temyiz, çağrı", "ph": "/əˈpiːl/"},
    "application": {"tr": "başvuru, müracaat, yazılım uygulaması", "ph": "/ˌæplɪˈkeɪʃn/"},
    "appoint": {"tr": "atamak, görevlendirmek, belirlemek", "ph": "/əˈpɔɪnt/"},
    "appreciate": {"tr": "takdir etmek, minnettar olmak, değeri artmak", "ph": "/əˈpriːʃieɪt/"},
    "approach": {"tr": "yaklaşmak; yaklaşım, yöntem", "ph": "/əˈprəʊtʃ/"},
    "appropriate": {"tr": "uygun, yerinde, münasip", "ph": "/əˈprəʊpriət/"},
    "approval": {"tr": "onay, kabul, rıza", "ph": "/əˈpruːvl/"},
    "approve": {"tr": "onaylamak, uygun bulmak", "ph": "/əˈpruːv/"},
    "arise": {"tr": "ortaya çıkmak, baş göstermek, kaynaklanmak", "ph": "/əˈraɪz/"},
    "armed": {"tr": "silahlı, donanımlı", "ph": "/ɑːmd/"},
    "arms": {"tr": "silahlar, cephane", "ph": "/ɑːmz/"},
    "artificial": {"tr": "yapay, suni, sahte", "ph": "/ˌɑːtɪˈfɪʃl/"},
    "aside": {"tr": "bir kenara, ayrı, bir tarafa", "ph": "/əˈsaɪd/"},
    "aspect": {"tr": "yön, boyut, veche, açı", "ph": "/ˈæspekt/"},
    "assess": {"tr": "değerlendirmek, paha biçmek", "ph": "/əˈses/"},
    "assessment": {"tr": "değerlendirme, ölçme, takdir", "ph": "/əˈsesmənt/"},
    "assignment": {"tr": "ödev, görev, atama", "ph": "/əˈsaɪnmənt/"},
    "assist": {"tr": "yardım etmek, desteklemek", "ph": "/əˈsɪst/"},
    "assistance": {"tr": "yardım, destek", "ph": "/əˈsɪstəns/"},
    "associate": {"tr": "ilişkilendirmek, bağdaştırmak; ortak", "ph": "/əˈsəʊʃieɪt/"},
    "associated": {"tr": "bağlantılı, ilişkili", "ph": "/əˈsəʊʃieɪtɪd/"},
    "association": {"tr": "dernek, birlik, ilişkilendirme", "ph": "/əˌsəʊʃiˈeɪʃn/"},
    "assume": {"tr": "varsaymak, üstlenmek (görev)", "ph": "/əˈsjuːm/"},
    "assumption": {"tr": "varsayım, faraziye", "ph": "/əˈsʌmpʃn/"},
    "attempt": {"tr": "girişimde bulunmak, denemek; girişim, teşebbüs", "ph": "/əˈtempt/"},
    "attitude": {"tr": "tutum, tavır, yaklaşım", "ph": "/ˈætɪtjuːd/"},
    "attract": {"tr": "çekmek, cezbetmek", "ph": "/əˈtrækt/"},
    "attraction": {"tr": "cazibe, çekim merkezi, ilgi", "ph": "/əˈtrækʃn/"},
    "attractive": {"tr": "çekici, cazip, alımlı", "ph": "/əˈtræktɪv/"},
    "authority": {"tr": "yetki, otorite, yetkili merci", "ph": "/ɔːˈθɒrəti/"},
    "automatic": {"tr": "otomatik, kendiliğinden işleyen", "ph": "/ˌɔːtəˈmætɪk/"},
    "automatically": {"tr": "otomatikman, kendiliğinden", "ph": "/ˌɔːtəˈmætɪkli/"},
    "awareness": {"tr": "farkındalık, bilinç", "ph": "/əˈweənəs/"},
    "backward": {"tr": "geriye doğru, geriye", "ph": "/ˈbækwəd/"},
    "backwards": {"tr": "geriye doğru, arkaya doğru", "ph": "/ˈbækwədz/"},
    "bacteria": {"tr": "bakteri", "ph": "/bækˈtɪəriə/"},
    "bake": {"tr": "fırında pişirmek", "ph": "/beɪk/"},
    "balance": {"tr": "denge; dengelemek", "ph": "/ˈbæləns/"},
    "barrier": {"tr": "engel, bariyer, set", "ph": "/ˈbæriə(r)/"},
    "basic": {"tr": "temel, esas, basit", "ph": "/ˈbeɪsɪk/"},
    "basically": {"tr": "temelde, aslında, esasen", "ph": "/ˈbeɪsɪkli/"},
    "basis": {"tr": "temel, esas, dayanak", "ph": "/ˈbeɪsɪs/"},
    "battery": {"tr": "pil, akü, batarya", "ph": "/ˈbætəri/"},
    "battle": {"tr": "savaş, muharebe, mücadele", "ph": "/ˈbætl/"},
    "beauty": {"tr": "güzellik, zarafet", "ph": "/ˈbjuːti/"},
    "beg": {"tr": "yalvarmak, rica etmek, dilenmek", "ph": "/beɡ/"},
    "behave": {"tr": "davranmak, uslu durmak", "ph": "/bɪˈheɪv/"},
    "belief": {"tr": "inanç, kanaat, iman", "ph": "/bɪˈliːf/"},
    "bend": {"tr": "bükülmek, eğilmek; viraj", "ph": "/bend/"},
    "benefit": {"tr": "fayda, yarar; yararlanmak", "ph": "/ˈbenɪfɪt/"},
    "bent": {"tr": "bükülmüş, eğik, kıvrık", "ph": "/bent/"},
    "bet": {"tr": "bahse girmek; bahis", "ph": "/bet/"},
    "beyond": {"tr": "ötesinde, aşan, öteye", "ph": "/bɪˈjɒnd/"},
    "bill": {"tr": "fatura, hesap, yasa tasarısı", "ph": "/bɪl/"},
    "bitter": {"tr": "acı (tat), kırgın, şiddetli", "ph": "/ˈbɪtə(r)/"},
    "blame": {"tr": "suçlamak, sorumlu tutmak; suç", "ph": "/bleɪm/"},
    "blind": {"tr": "kör, görme engelli; panjur", "ph": "/blaɪnd/"},
    "block": {"tr": "engellemek, tıkamak; blok, apartman bloğu", "ph": "/blɒk/"},
    "blonde": {"tr": "sarışın", "ph": "/blɒnd/"},
    "bomb": {"tr": "bomba; bombalamak", "ph": "/bɒm/"},
    "bond": {"tr": "bağ, ilişki, senet; bağlanmak", "ph": "/bɒnd/"},
    "border": {"tr": "sınır, hudut; sınırlamak", "ph": "/ˈbɔːdə(r)/"},
    "bother": {"tr": "rahatsız etmek, canını sıkmak; zahmet", "ph": "/ˈbɒðə(r)/"},
    "branch": {"tr": "dal, şube, branş", "ph": "/brɑːntʃ/"},
    "brand": {"tr": "marka; damgalamak", "ph": "/brænd/"},
    "brave": {"tr": "cesur, yürekli, yiğit", "ph": "/breɪv/"},
    "breath": {"tr": "nefes, soluk", "ph": "/breθ/"},
    "breathe": {"tr": "nefes almak, solumak", "ph": "/briːð/"},
    "breathing": {"tr": "nefes alma, solunum", "ph": "/ˈbriːðɪŋ/"},
    "bride": {"tr": "gelin", "ph": "/braɪd/"},
    "brief": {"tr": "kısa, öz; özetlemek", "ph": "/briːf/"},
    "briefly": {"tr": "kısaca, özetle", "ph": "/ˈbriːfli/"},
    "broad": {"tr": "geniş, kapsamlı, engin", "ph": "/brɔːd/"},
    "broadcast": {"tr": "yayınlamak; radyo/tv yayını", "ph": "/ˈbrɔːdkɑːst/"},
    "budget": {"tr": "bütçe; bütçe yapmak", "ph": "/ˈbʌdʒɪt/"},
    "bullet": {"tr": "kurşun, mermi", "ph": "/ˈbʊlɪt/"},
    "bunch": {"tr": "demet, salkım, grup", "ph": "/bʌntʃ/"},
    "burn": {"tr": "yanmak, yakmak; yanık", "ph": "/bɜːn/"},
    "burst": {"tr": "patlamak, fırlamak; patlama", "ph": "/bɜːst/"},
    "bury": {"tr": "gömmek, defnetmek", "ph": "/ˈberi/"},
    "bush": {"tr": "çalı, çalı kümesi", "ph": "/bʊʃ/"},
    "cable": {"tr": "kablo, halat, telgraf", "ph": "/ˈkeɪbl/"},
    "calculate": {"tr": "hesaplamak, hesap etmek", "ph": "/ˈkælkjuleɪt/"},
    "calm": {"tr": "sakin, dingin, huzurlu; sakinleştirmek", "ph": "/kɑːm/"},
    "campaign": {"tr": "kampanya, sefer; kampanya yürütmek", "ph": "/kæmˈpeɪn/"},
    "campus": {"tr": "kampüs, yerleşke", "ph": "/ˈkæmpəs/"},
    "cancel": {"tr": "iptal etmek, geçersiz kılmak", "ph": "/ˈkænsl/"},
    "cancer": {"tr": "kanser", "ph": "/ˈkænsə(r)/"},
    "candidate": {"tr": "aday, namzet", "ph": "/ˈkændɪdət/"},
    "capable": {"tr": "yetenekli, muktedir, yapabilir", "ph": "/ˈkeɪpəbl/"},
    "capacity": {"tr": "kapasite, hacim, yetenek", "ph": "/kəˈpæsəti/"},
    "capture": {"tr": "yakalamak, ele geçirmek, tutsak etmek", "ph": "/ˈkæptʃə(r)/"},
    "careless": {"tr": "dikkatsiz, özensiz, kayıtsız", "ph": "/ˈkeələs/"},
    "category": {"tr": "kategori, sınıf, tür", "ph": "/ˈkætəɡəri/"},
    "cease": {"tr": "durmak, son vermek, kesilmek", "ph": "/siːs/"},
    "ceiling": {"tr": "tavan", "ph": "/ˈsiːlɪŋ/"},
    "celebrate": {"tr": "kutlamak, tebrik etmek", "ph": "/ˈselɪbreɪt/"},
    "celebration": {"tr": "kutlama, şölen", "ph": "/ˌselɪˈbreɪʃn/"},
    "cell": {"tr": "hücre, cep telefonu, bölme", "ph": "/sel/"},
    "century": {"tr": "yüzyıl, asır", "ph": "/ˈsentʃəri/"},
    "ceremony": {"tr": "tören, merasim", "ph": "/ˈserəməni/"},
    "chain": {"tr": "zincir; zincirlemek", "ph": "/tʃeɪn/"},
    "challenge": {"tr": "meydan okuma, zorluk; meydan okumak", "ph": "/ˈtʃælɪndʒ/"},
    "chamber": {"tr": "oda, meclis odası, bölme", "ph": "/ˈtʃeɪmbə(r)/"},
    "champion": {"tr": "şampiyon, birinci", "ph": "/ˈtʃæmpiən/"},
    "championship": {"tr": "şampiyona, birincilik", "ph": "/ˈtʃæmpiənʃɪp/"},
    "channel": {"tr": "kanal, mecra; yönlendirmek", "ph": "/ˈtʃænl/"},
    "chapter": {"tr": "bölüm (kitap), kısım", "ph": "/ˈtʃæptə(r)/"},
    "charge": {"tr": "şarj etmek, ücret talep etmek, suçlamak; ücret", "ph": "/tʃɑːdʒ/"},
    "chart": {"tr": "grafik, çizelge, tablo", "ph": "/tʃɑːt/"},
    "chase": {"tr": "kovalamak, takip etmek; kovalama", "ph": "/tʃeɪs/"},
    "cheek": {"tr": "yanak", "ph": "/tʃiːk/"},
    "chest": {"tr": "göğüs, sandık", "ph": "/tʃest/"},
    "chief": {"tr": "başkan, şef, lider; başlıca, ana", "ph": "/tʃiːf/"},
    "childhood": {"tr": "çocukluk, çocukluk dönemi", "ph": "/ˈtʃaɪldhʊd/"},
    "chip": {"tr": "çip, patates cipsi, yonga", "ph": "/tʃɪp/"},
    "circumstance": {"tr": "durum, koşul, hal", "ph": "/ˈsɜːkəmstəns/"},
    "citizen": {"tr": "vatandaş, yurttaş", "ph": "/ˈsɪtɪzn/"},
    "civil": {"tr": "sivil, medeni, kibar", "ph": "/ˈsɪvl/"},
    "claim": {"tr": "iddia etmek, talep etmek; iddia, hak", "ph": "/kleɪm/"},
    "clarify": {"tr": "açıklığa kavuşturmak, netleştirmek", "ph": "/ˈklærəfaɪ/"},
    "classic": {"tr": "klasik, seçkin; klasik eser", "ph": "/ˈklæsɪk/"},
    "client": {"tr": "müşteri, danışan, müvekkil", "ph": "/ˈklaɪənt/"},
    "cliff": {"tr": "uçurum, sarp kayalık", "ph": "/klɪf/"},
    "clinic": {"tr": "klinik, dispanser", "ph": "/ˈklɪnɪk/"},
    "close": {"tr": "kapatmak; yakın, samimi", "ph": "/kləʊz/"},
    "closely": {"tr": "yakından, dikkatle, sıkıca", "ph": "/ˈkləʊsli/"},
    "clue": {"tr": "ipucu, emare", "ph": "/kluː/"},
    "collapse": {"tr": "çökmek, yıkılmak, bayılmak; çöküş", "ph": "/kəˈlæps/"},
    "collection": {"tr": "koleksiyon, toplama, derleme", "ph": "/kəˈlekʃn/"},
    "collective": {"tr": "ortaklaşa, kolektif, toplu", "ph": "/kəˈlektɪv/"},
    "combination": {"tr": "kombinasyon, birleşim, sentez", "ph": "/ˌkɒmbɪˈneɪʃn/"},
    "combine": {"tr": "birleştirmek, harmanlamak, kombine etmek", "ph": "/kəmˈbaɪn/"},
    "comfort": {"tr": "rahatlık, konfor, teselli; rahatlatmak", "ph": "/ˈkʌmfət/"},
    "command": {"tr": "komuta etmek, emretmek; emir, komuta", "ph": "/kəˈmɑːnd/"},
    "commercial": {"tr": "ticari, reklam filmi", "ph": "/kəˈmɜːʃl/"},
    "commission": {"tr": "komisyon, kurul, görevlendirme", "ph": "/kəˈmɪʃn/"},
    "commit": {"tr": "işlemek (suç), adamak, taahhüt etmek", "ph": "/kəˈmɪt/"},
    "commitment": {"tr": "bağlılık, taahhüt, adanmışlık", "ph": "/kəˈmɪtmənt/"},
    "committee": {"tr": "komite, kurul, heyet", "ph": "/kəˈmɪti/"},
    "common": {"tr": "yaygın, ortak, bilinen", "ph": "/ˈkɒmən/"},
    "commonly": {"tr": "genellikle, yaygın olarak", "ph": "/ˈkɒmənli/"},
    "complex": {"tr": "karmaşık, kompleks, tesis", "ph": "/ˈkɒmpleks/"},
    "complicated": {"tr": "çetrefilli, karmaşık, zor", "ph": "/ˈkɒmplɪkeɪtɪd/"},
    "component": {"tr": "bileşen, parça, unsur", "ph": "/kəmˈpəʊnənt/"},
    "compose": {"tr": "bestelemek, oluşturmak, yazmak", "ph": "/kəmˈpəʊz/"},
    "composition": {"tr": "kompozisyon, beste, yapılış", "ph": "/ˌkɒmpəˈzɪʃn/"},
    "compound": {"tr": "bileşik, bileşim; birleştirmek", "ph": "/ˈkɒmpaʊnd/"},
    "comprehensive": {"tr": "kapsamlı, etraflı, geniş", "ph": "/ˌkɒmprɪˈhensɪv/"},
    "concentrate": {"tr": "odaklanmak, yoğunlaşmak", "ph": "/ˈkɒnsntreɪt/"},
    "concentration": {"tr": "konsantrasyon, yoğunlaşma, derişim", "ph": "/ˌkɒnsnˈtreɪʃn/"},
    "concept": {"tr": "kavram, fikir, konsept", "ph": "/ˈkɒnsept/"},
    "concern": {"tr": "endişe, kaygı; ilgilendirmek", "ph": "/kənˈsɜːn/"},
    "concerned": {"tr": "endişeli, kaygılı, ilgili", "ph": "/kənˈsɜːnd/"},
    "conclude": {"tr": "sonuçlandırmak, karara bağlamak", "ph": "/kənˈkluːd/"},
    "conclusion": {"tr": "sonuç, netice, yargı", "ph": "/kənˈkluːʒn/"},
    "conduct": {"tr": "yürütmek, yönetmek; davranış", "ph": "/kənˈdʌkt/"},
    "confidence": {"tr": "güven, özgüven, inanç", "ph": "/ˈkɒnfɪdəns/"},
    "confident": {"tr": "kendinden emin, özgüvenli", "ph": "/ˈkɒnfɪdənt/"},
    "confirm": {"tr": "doğrulamak, onaylamak, teyit etmek", "ph": "/kənˈfɜːm/"},
    "conflict": {"tr": "çatışma, anlaşmazlık; çatışmak", "ph": "/ˈkɒnflɪkt/"},
    "confuse": {"tr": "kafasını karıştırmak, yanıltmak", "ph": "/kənˈfjuːz/"},
    "confused": {"tr": "kafası karışık, şaşkın", "ph": "/kənˈfjuːzd/"},
    "confusing": {"tr": "kafa karıştırıcı, karmaşık", "ph": "/kənˈfjuːzɪŋ/"},
    "connection": {"tr": "bağlantı, ilişki, bağ", "ph": "/kəˈnekʃn/"},
    "consequence": {"tr": "sonuç, netice, akıbet", "ph": "/ˈkɒnsɪkwəns/"},
    "conservative": {"tr": "muhafazakar, tutucu, temkinli", "ph": "/kənˈsɜːvətɪv/"},
    "considerable": {"tr": "kayda değer, önemli miktarda", "ph": "/kənˈsɪdərəbl/"},
    "consideration": {"tr": "düşünce, değerlendirme, inceleme", "ph": "/kənˌsɪdəˈreɪʃn/"},
    "consist": {"tr": "-den oluşmak, meydana gelmek", "ph": "/kənˈsɪst/"},
    "consistent": {"tr": "tutarlı, istikrarlı, dengeli", "ph": "/kənˈsɪstənt/"},
    "constant": {"tr": "sürekli, sabit, daimi", "ph": "/ˈkɒnstənt/"},
    "constantly": {"tr": "sürekli olarak, durmaksızın", "ph": "/ˈkɒnstəntli/"},
    "construct": {"tr": "inşa etmek, kurmak, oluşturmak", "ph": "/kənˈstrʌkt/"},
    "construction": {"tr": "inşaat, yapım, yapı", "ph": "/kənˈstrʌkʃn/"},
    "consume": {"tr": "tüketmek, harcamak, yemek", "ph": "/kənˈsjuːm/"},
    "consumer": {"tr": "tüketici, alıcı", "ph": "/kənˈsjuːmə(r)/"},
    "contact": {"tr": "temasa geçmek; irtibat, temas", "ph": "/ˈkɒntækt/"},
    "contemporary": {"tr": "çağdaş, modern, akran", "ph": "/kənˈtemprəri/"},
    "contest": {"tr": "yarışma, mücadele; itiraz etmek", "ph": "/ˈkɒntest/"},
    "continuous": {"tr": "kesintisiz, sürekli, aralıksız", "ph": "/kənˈtɪnjuəs/"},
    "contrast": {"tr": "karşıtlık, tezat; karşılaştırmak", "ph": "/ˈkɒntrɑːst/"},
    "contribute": {"tr": "katkıda bulunmak, katkı sağlamak", "ph": "/kənˈtrɪbjuːt/"},
    "contribution": {"tr": "katkı, hisse, bağış", "ph": "/ˌkɒntrɪˈbjuːʃn/"},
    "convenient": {"tr": "kullanışlı, elverişli, uygun", "ph": "/kənˈviːniənt/"},
    "convention": {"tr": "kongre, kurultay, gelenek", "ph": "/kənˈvenʃn/"},
    "conventional": {"tr": "geleneksel, alışılagelmiş", "ph": "/kənˈvenʃənl/"},
    "convert": {"tr": "dönüştürmek, çevirmek, değiştirmek", "ph": "/kənˈvɜːt/"},
    "convince": {"tr": "ikna etmek, inandırmak", "ph": "/kənˈvɪns/"},
    "convinced": {"tr": "ikna olmuş, emin", "ph": "/kənˈvɪnst/"},
    "cool": {"tr": "serin, havalı; sakinleşmek", "ph": "/kuːl/"},
    "cope": {"tr": "başa çıkmak, üstesinden gelmek", "ph": "/kəʊp/"},
    "core": {"tr": "çekirdek, öz, ana merkez", "ph": "/kɔː(r)/"},
    "corporate": {"tr": "kurumsal, şirkete ait", "ph": "/ˈkɔːpərət/"},
    "correctly": {"tr": "doğru bir şekilde, düzgünce", "ph": "/kəˈrektli/"},
    "courage": {"tr": "cesaret, yüreklilik", "ph": "/ˈkʌrɪdʒ/"},
    "court": {"tr": "mahkeme, kort, avlu", "ph": "/kɔːt/"},
    "cover": {"tr": "örtmek, kaplamak; kapak, örtü", "ph": "/ˈkʌvə(r)/"},
    "covered": {"tr": "örtülü, kaplı", "ph": "/ˈkʌvəd/"},
    "craft": {"tr": "zanaat, el sanatı, ustalık, zanaat yapmak", "ph": "/krɑːft/"},
    "crash": {"tr": "çarpmak, kaza yapmak; kaza, gürültü", "ph": "/kræʃ/"},
    "creative": {"tr": "yaratıcı, üretken", "ph": "/kriˈeɪtɪv/"},
    "creature": {"tr": "yaratık, canlı, varlık", "ph": "/ˈkriːtʃə(r)/"},
    "credit": {"tr": "kredi, itibar, takdir", "ph": "/ˈkredɪt/"},
    "crew": {"tr": "mürettebat, ekip, tayfa", "ph": "/kruː/"},
    "crime": {"tr": "suç, cürüm", "ph": "/kraɪm/"},
    "criminal": {"tr": "suçlu, sabıkalı; cezai", "ph": "/ˈkrɪmɪnl/"},
    "crisis": {"tr": "kriz, bunalım, buhran", "ph": "/ˈkraɪsɪs/"},
    "criterion": {"tr": "kriter, ölçüt, kıstas", "ph": "/kraɪˈtɪəriən/"},
    "critical": {"tr": "kritik, hayati, eleştirel", "ph": "/ˈkrɪtɪkl/"},
    "criticism": {"tr": "eleştiri, tenkit", "ph": "/ˈkrɪtɪsɪzəm/"},
    "criticize": {"tr": "eleştirmek, tenkit etmek", "ph": "/ˈkrɪtɪsaɪz/"},
    "crop": {"tr": "ürün, mahsul, ekin; kırpmak", "ph": "/krɒp/"},
    "crucial": {"tr": "çok önemli, hayati, can alıcı", "ph": "/ˈkruːʃl/"},
    "cruel": {"tr": "zalim, acımasız, merhametsiz", "ph": "/ˈkruːəl/"},
    "culture": {"tr": "kültür, ekin", "ph": "/ˈkʌltʃə(r)/"},
    "cure": {"tr": "tedavi etmek, iyileştirmek; çare, şifa", "ph": "/kjʊə(r)/"},
    "current": {"tr": "mevcut, güncel; akım, cereyan", "ph": "/ˈkʌrənt/"},
    "currently": {"tr": "şu anda, halen, halihazırda", "ph": "/ˈkʌrəntli/"},
    "curve": {"tr": "kıvrılmak, bükülmek; eğri, kavis", "ph": "/kɜːv/"},
    "curved": {"tr": "kavisli, eğri, kıvrımlı", "ph": "/kɜːvd/"},
    "custom": {"tr": "gelenek, adet, görenek; gümrük", "ph": "/ˈkʌstəm/"},
    "damage": {"tr": "zarar vermek, hasara uğratmak; hasar, zarar", "ph": "/ˈdæmɪdʒ/"},
    "deal": {"tr": "anlaşma, uzlaşma; ilgilenmek, dağıtmak", "ph": "/diːl/"},
    "debate": {"tr": "münazara etmek, tartışmak; münazara", "ph": "/dɪˈbeɪt/"},
    "debt": {"tr": "borç", "ph": "/det/"},
    "decade": {"tr": "on yıl, dekat", "ph": "/ˈdekeɪd/"},
    "decay": {"tr": "çürümek, bozulmak; çürüme", "ph": "/dɪˈkeɪ/"},
    "deceive": {"tr": "kandırmak, aldatmak, yanıltmak", "ph": "/dɪˈsiːv/"},
    "declare": {"tr": "ilan etmek, beyan etmek, bildirmek", "ph": "/dɪˈkleə(r)/"},
    "decline": {"tr": "reddetmek, gerilemek; düşüş, azalma", "ph": "/dɪˈklaɪn/"},
    "decorate": {"tr": "dekore etmek, süslemek, donatmak", "ph": "/ˈdekəreɪt/"},
    "decrease": {"tr": "azalmak, düşmek; azalma, düşüş", "ph": "/dɪˈkriːs/"},
    "dedicate": {"tr": "adamak, ithaf etmek", "ph": "/ˈdedɪkeɪt/"},
    "defeat": {"tr": "yenmek, mağlup etmek; yenilgi", "ph": "/dɪˈfiːt/"},
    "defence": {"tr": "savunma, müdafaa", "ph": "/dɪˈfens/"},
    "defend": {"tr": "savunmak, korumak", "ph": "/dɪˈfend/"},
    "define": {"tr": "tanımlamak, tarif etmek, belirlemek", "ph": "/dɪˈfaɪn/"},
    "definite": {"tr": "kesin, belirgin, net", "ph": "/ˈdefɪnət/"},
    "definitely": {"tr": "kesinlikle, şüphesiz", "ph": "/ˈdefɪnətli/"},
    "definition": {"tr": "tanım, açıklama, tarif", "ph": "/ˌdefɪˈnɪʃn/"},
    "degree": {"tr": "derece, rütbe, diploma derecesi", "ph": "/dɪˈɡriː/"},
    "delay": {"tr": "ertelemek, geciktirmek; gecikme", "ph": "/dɪˈleɪ/"},
    "deliberate": {"tr": "kasıtlı, planlı, temkinli", "ph": "/dɪˈlɪbərət/"},
    "deliberately": {"tr": "kasten, bilerek, mahsus", "ph": "/dɪˈlɪbərətli/"},
    "deliver": {"tr": "teslim etmek, ulaştırmak, doğum yaptırmak", "ph": "/dɪˈlɪvə(r)/"},
    "delivery": {"tr": "teslimat, dağıtım, doğum", "ph": "/dɪˈlɪvəri/"},
    "demand": {"tr": "talep etmek, istemek; talep, istek", "ph": "/dɪˈmɑːnd/"},
    "demonstrate": {"tr": "göstermek, kanıtlamak, gösteri yapmak", "ph": "/ˈdemənstreɪt/"},
    "dentist": {"tr": "diş hekimi, dişçi", "ph": "/ˈdentɪst/"},
    "deny": {"tr": "inkar etmek, reddetmek, yalanlamak", "ph": "/dɪˈnaɪ/"},
    "depart": {"tr": "ayrılmak, hareket etmek, kalkmak", "ph": "/dɪˈpɑːt/"},
    "department": {"tr": "bölüm, departman, daire", "ph": "/dɪˈpɑːtmənt/"},
    "departure": {"tr": "kalkış, ayrılış, hareket", "ph": "/dɪˈpɑːtʃə(r)/"},
    "depend": {"tr": "bağlı olmak, güvenmek, bel bağlamak", "ph": "/dɪˈpend/"},
    "deposit": {"tr": "para yatırmak, depozito bırakmak; mevduat", "ph": "/dɪˈpɒzɪt/"},
    "depress": {"tr": "moralini bozmak, canını sıkmak, çökertmek", "ph": "/dɪˈpres/"},
    "depressed": {"tr": "morali bozuk, çökkün, depresyonda", "ph": "/dɪˈprest/"},
    "depth": {"tr": "derinlik, enginlik", "ph": "/depθ/"},
    "derive": {"tr": "türetmek, -den elde etmek, kaynaklanmak", "ph": "/dɪˈraɪv/"},
    "describe": {"tr": "tanımlamak, tasvir etmek, tarif etmek", "ph": "/dɪˈskraɪb/"},
    "description": {"tr": "tanım, tasvir, açıklama", "ph": "/dɪˈskrɪpʃn/"},
    "desert": {"tr": "çöl; terk etmek", "ph": "/ˈdezət/"},
    "deserve": {"tr": "hak etmek, layık olmak", "ph": "/dɪˈzɜːv/"},
    "design": {"tr": "tasarlamak; tasarım, dizayn", "ph": "/dɪˈzaɪn/"},
    "desire": {"tr": "arzulamak, çok istemek; arzu, istek", "ph": "/dɪˈzaɪə(r)/"},
    "desperate": {"tr": "çaresiz, umutsuz, gözü dönmüş", "ph": "/ˈdespərət/"},
    "despite": {"tr": "-e rağmen, -e karşın", "ph": "/dɪˈspaɪt/"},
    "destination": {"tr": "varış yeri, hedef yer, menzil", "ph": "/ˌdestɪˈneɪʃn/"},
    "destroy": {"tr": "yıkmak, yok etmek, imha etmek", "ph": "/dɪˈstrɔɪ/"},
    "detail": {"tr": "ayrıntı, detay; detaylandırmak", "ph": "/ˈdiːteɪl/"},
    "detailed": {"tr": "ayrıntılı, detaylı, kapsamlı", "ph": "/ˈdiːteɪld/"},
    "detect": {"tr": "tespit etmek, belirlemek, sezmek", "ph": "/dɪˈtekt/"},
    "determination": {"tr": "azim, kararlılık, saptama", "ph": "/dɪˌtɜːmɪˈneɪʃn/"},
    "determine": {"tr": "belirlemek, saptamak, kararlaştırmak", "ph": "/dɪˈtɜːmɪn/"},
    "determined": {"tr": "kararlı, azimli", "ph": "/dɪˈtɜːmɪnd/"},
    "develop": {"tr": "geliştirmek, gelişmek, ortaya çıkmak", "ph": "/dɪˈveləp/"},
    "development": {"tr": "gelişim, gelişme, kalkınma", "ph": "/dɪˈveləpmənt/"},
    "device": {"tr": "cihaz, alet, aygıt", "ph": "/dɪˈvaɪs/"},
    "devote": {"tr": "adamak, vakfetmek, ayırmak", "ph": "/dɪˈvəʊt/"},
    "differ": {"tr": "farklı olmak, uyuşmamak, ayrılmak", "ph": "/ˈdɪfə(r)/"},
    "difference": {"tr": "fark, ayrım, değişiklik", "ph": "/ˈdɪfrəns/"},
    "different": {"tr": "farklı, değişik, başka", "ph": "/ˈdɪfrənt/"},
    "differently": {"tr": "farklı bir şekilde, değişikçe", "ph": "/ˈdɪfrəntli/"},
    "difficult": {"tr": "zor, güç, çetin", "ph": "/ˈdɪfɪkəlt/"},
    "difficulty": {"tr": "zorluk, güçlük, sıkıntı", "ph": "/ˈdɪfɪkəlti/"},
    "dig": {"tr": "kazmak, deşmek", "ph": "/dɪɡ/"},
    "digital": {"tr": "dijital, sayısal", "ph": "/ˈdɪdʒɪtl/"},
    "dinner": {"tr": "akşam yemeği", "ph": "/ˈdɪnə(r)/"},
    "direct": {"tr": "yönetmek, yönlendirmek; doğrudan, direkt", "ph": "/dəˈrekt/"},
    "direction": {"tr": "yön, istikamet, talimat", "ph": "/dəˈrekʃn/"},
    "directly": {"tr": "doğrudan, aracısız, derhal", "ph": "/dəˈrektli/"},
    "director": {"tr": "yönetmen, müdür, direktör", "ph": "/dəˈrektə(r)/"},
    "dirt": {"tr": "kir, pislik, toprak", "ph": "/dɜːt/"},
    "dirty": {"tr": "kirli, pis, lekeli", "ph": "/ˈdɜːti/"},
    "disadvantage": {"tr": "dezavantaj, sakınca, eksi yön", "ph": "/ˌdɪsədˈvɑːntɪdʒ/"},
    "disagree": {"tr": "aynı fikirde olmamak, uyuşmamak", "ph": "/ˌdɪsəˈɡriː/"},
    "disappear": {"tr": "gözden kaybolmak, yok olmak", "ph": "/ˌdɪsəˈpɪə(r)/"},
    "disappoint": {"tr": "hayal kırıklığına uğratmak", "ph": "/ˌdɪsəˈpɔɪnt/"},
    "disappointed": {"tr": "hayal kırıklığına uğramış", "ph": "/ˌdɪsəˈpɔɪntɪd/"},
    "disaster": {"tr": "felaket, afet, facia", "ph": "/dɪˈzɑːstə(r)/"},
    "discipline": {"tr": "disiplin, intizam; disipline etmek", "ph": "/ˈdɪsəplɪn/"},
    "discount": {"tr": "indirim, iskonto; indirim yapmak", "ph": "/ˈdɪskaʊnt/"},
    "discover": {"tr": "keşfetmek, bulmak, ortaya çıkarmak", "ph": "/dɪˈskʌvə(r)/"},
    "discovery": {"tr": "keşif, buluş", "ph": "/dɪˈskʌvəri/"},
    "discuss": {"tr": "tartışmak, görüşmek, ele almak", "ph": "/dɪˈskʌs/"},
    "discussion": {"tr": "tartışma, müzakere, görüşme", "ph": "/dɪˈskʌʃn/"},
    "disease": {"tr": "hastalık, rahatsızlık", "ph": "/dɪˈziːz/"},
    "dish": {"tr": "yemek, tabak, bulaşık", "ph": "/dɪʃ/"},
    "dismiss": {"tr": "kovmak, işten çıkarmak, aklından çıkarmak", "ph": "/dɪsˈmɪs/"},
    "display": {"tr": "sergilemek, göstermek; ekran, sergi", "ph": "/dɪˈspleɪ/"},
    "distance": {"tr": "mesafe, uzaklık, ara", "ph": "/ˈdɪstəns/"},
    "distant": {"tr": "uzak, ırak, mesafeli", "ph": "/ˈdɪstənt/"},
    "distinguish": {"tr": "ayırt etmek, farkı görmek", "ph": "/dɪˈstɪŋɡwɪʃ/"},
    "distribute": {"tr": "dağıtmak, bölüştürmek", "ph": "/dɪˈstrɪbjuːt/"},
    "distribution": {"tr": "dağıtım, bölüşüm, yayılım", "ph": "/ˌdɪstrɪˈbjuːʃn/"},
    "district": {"tr": "ilçe, bölge, semt", "ph": "/ˈdɪstrɪkt/"},
    "divide": {"tr": "bölmek, paylaştırmak, ayrılmak", "ph": "/dɪˈvaɪd/"},
    "division": {"tr": "bölüm, bölme, ayrılma", "ph": "/dɪˈvɪʒn/"},
    "divorced": {"tr": "boşanmış", "ph": "/dɪˈvɔːst/"},
    "document": {"tr": "belge, doküman; belgelemek", "ph": "/ˈdɒkjumənt/"},
    "domestic": {"tr": "evcil, yerli, yurt içi, ailevi", "ph": "/dəˈmestɪk/"},
    "dominate": {"tr": "hakim olmak, hükmetmek, egemen olmak", "ph": "/ˈdɒmɪneɪt/"},
    "double": {"tr": "çift, iki katı; ikiye katlamak", "ph": "/ˈdʌbl/"},
    "doubt": {"tr": "şüphe etmek; şüphe, kuşku", "ph": "/daʊt/"},
    "down": {"tr": "aşağıya, aşağıda; inmiş", "ph": "/daʊn/"},
    "download": {"tr": "indirmek (dosya); indirme", "ph": "/ˌdaʊnˈləʊd/"},
    "dramatic": {"tr": "çarpıcı, dramatik, ani", "ph": "/drəˈmætɪk/"},
    "dramatically": {"tr": "büyük ölçüde, çarpıcı biçimde", "ph": "/drəˈmætɪkli/"},
    "drawer": {"tr": "çekmece", "ph": "/drɔː(r)/"},
    "drawing": {"tr": "çizim, resim yapma, karakalem", "ph": "/ˈdrɔːɪŋ/"},
    "dream": {"tr": "rüya görmek, hayal etmek; rüya, hayal", "ph": "/driːm/"},
    "dress": {"tr": "elbise; giyinmek, giydirmek", "ph": "/dres/"},
    "dressed": {"tr": "giyinmiş, kuşanmış", "ph": "/drest/"},
    "drink": {"tr": "içmek; içecek, meşrubat", "ph": "/drɪŋk/"},
    "drive": {"tr": "sürmek, araba kullanmak; sürüş, güdü", "ph": "/draɪv/"},
    "driver": {"tr": "şoför, sürücü", "ph": "/ˈdraɪvə(r)/"},
    "driving": {"tr": "araç kullanma, sürüş", "ph": "/ˈdraɪvɪŋ/"},
    "drop": {"tr": "düşürmek, damlatmak; damla, düşüş", "ph": "/drɒp/"},
    "drug": {"tr": "ilaç, uyuşturucu madde", "ph": "/drʌɡ/"},
    "drum": {"tr": "davul, bateri, varil", "ph": "/drʌm/"},
    "drunk": {"tr": "sarhoş, alkollü", "ph": "/drʌŋk/"},
    "dry": {"tr": "kuru, kurak; kurutmak, kurulamak", "ph": "/draɪ/"},
    "due": {"tr": "vadesi gelen, beklenen, uygun", "ph": "/djuː/"},
    "dust": {"tr": "toz; tozunu almak", "ph": "/dʌst/"},
    "duty": {"tr": "görev, vazife, gümrük vergisi", "ph": "/ˈdjuːti/"},
    "each": {"tr": "her biri, her", "ph": "/iːtʃ/"},
    "eager": {"tr": "istekli, hevesli, can atan", "ph": "/ˈiːɡə(r)/"},
    "ear": {"tr": "kulak", "ph": "/ɪə(r)/"},
    "early": {"tr": "erken, erkenden; ilk", "ph": "/ˈɜːli/"},
    "earn": {"tr": "para kazanmak, hak etmek", "ph": "/ɜːn/"},
    "earth": {"tr": "dünya, yeryüzü, toprak", "ph": "/ɜːθ/"},
    "easily": {"tr": "kolayca, rahatlıkla", "ph": "/ˈiːzəli/"},
    "east": {"tr": "doğu; doğuda", "ph": "/iːst/"},
    "eastern": {"tr": "doğuya ait, doğudaki", "ph": "/ˈiːstən/"},
    "easy": {"tr": "kolay, basit, rahat", "ph": "/ˈiːzi/"},
    "eat": {"tr": "yemek yemek, yemek", "ph": "/iːt/"},
    "economic": {"tr": "ekonomik, iktisadi", "ph": "/ˌiːkəˈnɒmɪk/"},
    "economy": {"tr": "ekonomi, iktisat, tasarruf", "ph": "/ɪˈkɒnəmi/"},
    "edge": {"tr": "kenar, kıyı, avantaj", "ph": "/edʒ/"},
    "edition": {"tr": "baskı, yayın, edisyon", "ph": "/ɪˈdɪʃn/"},
    "editor": {"tr": "editör, yayın yönetmeni", "ph": "/ˈedɪtə(r)/"},
    "educate": {"tr": "eğitmek, yetiştirmek", "ph": "/ˈedʒukeɪt/"},
    "educated": {"tr": "eğitimli, tahsilli", "ph": "/ˈedʒukeɪtɪd/"},
    "education": {"tr": "eğitim, öğretim, tahsil", "ph": "/ˌedʒuˈkeɪʃn/"},
    "educational": {"tr": "eğitici, eğitimle ilgili", "ph": "/ˌedʒuˈkeɪʃənl/"},
    "effect": {"tr": "etki, tesir, sonuç", "ph": "/ɪˈfekt/"},
    "effective": {"tr": "etkili, tesirli, geçerli", "ph": "/ɪˈfektɪv/"},
    "effectively": {"tr": "etkili bir şekilde, etkin biçimde", "ph": "/ɪˈfektɪvli/"},
    "efficient": {"tr": "verimli, etkili çalışan", "ph": "/ɪˈfɪʃnt/"},
    "effort": {"tr": "çaba, gayret, emek", "ph": "/ˈefət/"},
    "egg": {"tr": "yumurta", "ph": "/eɡ/"},
    "either": {"tr": "ya, ikisinden biri, de/da (olumsuzda)", "ph": "/ˈaɪðə(r)/"},
    "elderly": {"tr": "yaşlı, ihtiyar", "ph": "/ˈeldəli/"},
    "elect": {"tr": "seçmek (oyla)", "ph": "/ɪˈlekt/"},
    "election": {"tr": "seçim", "ph": "/ɪˈlekʃn/"},
    "electric": {"tr": "elektrikli, elektrikle çalışan", "ph": "/ɪˈlektrɪk/"},
    "electrical": {"tr": "elektriksel, elektrikle ilgili", "ph": "/ɪˈlektrɪkl/"},
    "electricity": {"tr": "elektrik", "ph": "/ɪˌlekˈtrɪsəti/"},
    "electronic": {"tr": "elektronik", "ph": "/ɪˌlekˈtrɒnɪk/"},
    "element": {"tr": "öğe, unsur, element", "ph": "/ˈelɪmənt/"},
    "elevator": {"tr": "asansör", "ph": "/ˈelɪveɪtə(r)/"},
    "eleven": {"tr": "on bir", "ph": "/ɪˈlevn/"},
    "else": {"tr": "başka, diğer", "ph": "/els/"},
    "elsewhere": {"tr": "başka yerde, başka bir yere", "ph": "/ˌelsˈweə(r)/"},
    "email": {"tr": "e-posta; e-posta göndermek", "ph": "/ˈiːmeɪl/"},
    "embarrassed": {"tr": "utanmış, mahcup olmuş", "ph": "/ɪmˈbærəst/"},
    "embarrassing": {"tr": "utanç verici, mahcup edici", "ph": "/ɪmˈbærəsɪŋ/"},
    "emerge": {"tr": "ortaya çıkmak, belirmek, doğmak", "ph": "/ɪˈmɜːdʒ/"},
    "emergency": {"tr": "acil durum, aciliyet", "ph": "/ɪˈmɜːdʒənsi/"},
    "emotion": {"tr": "duygu, his, coşku", "ph": "/ɪˈməʊʃn/"},
    "emotional": {"tr": "duygusal, hisli", "ph": "/ɪˈməʊʃənl/"},
    "emphasis": {"tr": "vurgu, önem", "ph": "/ˈemfəsɪs/"},
    "emphasize": {"tr": "vurgulamak, önemini belirtmek", "ph": "/ˈemfəsaɪz/"},
    "employ": {"tr": "işe almak, istihdam etmek, kullanmak", "ph": "/ɪmˈplɔɪ/"},
    "employee": {"tr": "çalışan, işçi, personel", "ph": "/ɪmˈplɔɪiː/"},
    "employer": {"tr": "işveren, patron", "ph": "/ɪmˈplɔɪə(r)/"},
    "employment": {"tr": "istihdam, iş, çalışma", "ph": "/ɪmˈplɔɪmənt/"},
    "empty": {"tr": "boş; boşaltmak", "ph": "/ˈempti/"},
    "enable": {"tr": "olanak sağlamak, imkan vermek, etkinleştirmek", "ph": "/ɪˈneɪbl/"},
    "encounter": {"tr": "karşılaşmak, rastlamak; karşılaşma", "ph": "/ɪnˈkaʊntə(r)/"},
    "encourage": {"tr": "cesaretlendirmek, teşvik etmek", "ph": "/ɪnˈkʌrɪdʒ/"},
    "end": {"tr": "bitmek, bitirmek; son, uç", "ph": "/end/"},
    "ending": {"tr": "son, bitiş, final", "ph": "/ˈendɪŋ/"},
    "enemy": {"tr": "düşman, hasım", "ph": "/ˈenəmi/"},
    "energy": {"tr": "enerji, güç, dinçlik", "ph": "/ˈenədʒi/"},
    "engage": {"tr": "dahil olmak, ilgilenmek, nişanlanmak", "ph": "/ɪnˈɡeɪdʒ/"},
    "engine": {"tr": "motor, lokomotif", "ph": "/ˈendʒɪn/"},
    "engineer": {"tr": "mühendis; tasarlamak", "ph": "/ˌendʒɪˈnɪə(r)/"},
    "engineering": {"tr": "mühendislik", "ph": "/ˌendʒɪˈnɪərɪŋ/"},
    "enhance": {"tr": "artırmak, geliştirmek, zenginleştirmek", "ph": "/ɪnˈhɑːns/"},
    "enjoy": {"tr": "zevk almak, keyfini çıkarmak, hoşlanmak", "ph": "/ɪnˈdʒɔɪ/"},
    "enormous": {"tr": "muazzam, devasa, çok büyük", "ph": "/ɪˈnɔːməs/"},
    "enough": {"tr": "yeterli, kafi, yeterince", "ph": "/ɪˈnʌf/"},
    "enquiry": {"tr": "soruşturma, danışma, bilgi alma", "ph": "/ɪnˈkwaɪəri/"},
    "ensure": {"tr": "sağlamak, garantiye almak, temin etmek", "ph": "/ɪnˈʃʊə(r)/"},
    "enter": {"tr": "girmek, içeri girmek, kaydetmek", "ph": "/ˈentə(r)/"},
    "entertain": {"tr": "eğlendirmek, ağırlamak", "ph": "/ˌentəˈteɪn/"},
    "entertainment": {"tr": "eğlence, gösteri", "ph": "/ˌentəˈteɪnmənt/"},
    "enthusiastic": {"tr": "hevesli, coşkulu, istekli", "ph": "/ɪnˌθjuːziˈæstɪk/"},
    "entire": {"tr": "tüm, bütün, eksiksiz", "ph": "/ɪnˈtaɪə(r)/"},
    "entirely": {"tr": "tamamen, bütünüyle", "ph": "/ɪnˈtaɪəli/"},
    "entry": {"tr": "giriş, katılım, girdi", "ph": "/ˈentri/"},
    "environment": {"tr": "çevre, ortam", "ph": "/ɪnˈvaɪrənmənt/"},
    "environmental": {"tr": "çevresel, çevreyle ilgili", "ph": "/ɪnˌvaɪrənˈmentl/"},
    "episode": {"tr": "bölüm (dizi), olay, hadise", "ph": "/ˈepɪsəʊd/"},
    "equal": {"tr": "eşit, denk; eşit olmak", "ph": "/ˈiːkwəl/"},
    "equally": {"tr": "eşit olarak, eşit derecede", "ph": "/ˈiːkwəli/"},
    "equipment": {"tr": "ekipman, donanım, araç gereç", "ph": "/ɪˈkwɪpmənt/"},
    "error": {"tr": "hata, kusur, yanlışlık", "ph": "/ˈerə(r)/"},
    "escape": {"tr": "kaçmak, kurtulmak; kaçış", "ph": "/ɪˈskeɪp/"},
    "especially": {"tr": "özellikle, bilhassa", "ph": "/ɪˈspeʃəli/"},
    "essay": {"tr": "deneme, makale, kompozisyon", "ph": "/ˈeseɪ/"},
    "essential": {"tr": "temel, vazgeçilmez, çok önemli", "ph": "/ɪˈsenʃl/"},
    "establish": {"tr": "kurmak, tesis etmek, kanıtlamak", "ph": "/ɪˈstæblɪʃ/"},
    "estate": {"tr": "mülk, arazi, emlak", "ph": "/ɪˈsteɪt/"},
    "estimate": {"tr": "tahmin etmek, değer biçmek; tahmin", "ph": "/ˈestɪmeɪt/"},
    "even": {"tr": "hatta, bile; eşit, çift (sayı)", "ph": "/ˈiːvn/"},
    "evening": {"tr": "akşam", "ph": "/ˈiːvnɪŋ/"},
    "event": {"tr": "etkinlik, olay, hadise", "ph": "/ɪˈvent/"},
    "eventually": {"tr": "sonunda, nihayetinde, eninde sonunda", "ph": "/ɪˈventʃuəli/"},
    "ever": {"tr": "hiç, şimdiye kadar, daima", "ph": "/ˈevə(r)/"},
    "every": {"tr": "her, her bir", "ph": "/ˈevri/"},
    "everybody": {"tr": "herkes", "ph": "/ˈevribɒdi/"},
    "everyone": {"tr": "herkes", "ph": "/ˈevriwʌn/"},
    "everything": {"tr": "her şey", "ph": "/ˈevriθɪŋ/"},
    "everywhere": {"tr": "her yer, her yere", "ph": "/ˈevriweə(r)/"},
    "evidence": {"tr": "kanıt, delil, bulgu", "ph": "/ˈevɪdəns/"},
    "evil": {"tr": "kötü, fena; kötülük, şer", "ph": "/ˈiːvl/"},
    "exact": {"tr": "kesin, tam, eksiksiz", "ph": "/ɪɡˈzækt/"},
    "exactly": {"tr": "kesinlikle, aynen, tam olarak", "ph": "/ɪɡˈzæktli/"},
    "exam": {"tr": "sınav, imtihan", "ph": "/ɪɡˈzæm/"},
    "examination": {"tr": "inceleme, muayene, sınav", "ph": "/ɪɡˌzæmɪˈneɪʃn/"},
    "examine": {"tr": "incelemek, muayene etmek, denetlemek", "ph": "/ɪɡˈzæmɪn/"},
    "example": {"tr": "örnek, misal", "ph": "/ɪɡˈzɑːmpl/"},
    "excellent": {"tr": "mükemmel, kusursuz, harika", "ph": "/ˈeksələnt/"},
    "except": {"tr": "-den başka, haricinde, dışında", "ph": "/ɪkˈsept/"},
    "exchange": {"tr": "değiş tokuş etmek, takas etmek; döviz", "ph": "/ɪksˈtʃeɪndʒ/"},
    "excited": {"tr": "heyecanlı, coşkulu", "ph": "/ɪkˈsaɪtɪd/"},
    "excitement": {"tr": "heyecan, coşku", "ph": "/ɪkˈsaɪtmənt/"},
    "exciting": {"tr": "heyecan verici, sürükleyici", "ph": "/ɪkˈsaɪtɪŋ/"},
    "excuse": {"tr": "mazeret, bahane; affetmek, bağışlamak", "ph": "/ɪkˈskjuːs/"},
    "executive": {"tr": "yönetici, idareci; yürütme", "ph": "/ɪɡˈzekjətɪv/"},
    "exercise": {"tr": "egzersiz yapmak, alıştırma yapmak; egzersiz", "ph": "/ˈeksəsaɪz/"},
    "exhibition": {"tr": "sergi, fuar, gösteri", "ph": "/ˌeksɪˈbɪʃn/"},
    "exist": {"tr": "var olmak, bulunmak, mevcut olmak", "ph": "/ɪɡˈzɪst/"},
    "existence": {"tr": "varlık, mevcudiyet, var oluş", "ph": "/ɪɡˈzɪstəns/"},
    "expand": {"tr": "genişletmek, büyütmek, yayılmak", "ph": "/ɪkˈspænd/"},
    "expect": {"tr": "beklemek, ummak, tahmin etmek", "ph": "/ɪkˈspekt/"},
    "expectation": {"tr": "beklenti, umut", "ph": "/ˌekspekˈteɪʃn/"},
    "expected": {"tr": "beklenen, umulan", "ph": "/ɪkˈspektɪd/"},
    "expense": {"tr": "masraf, gider, harcama", "ph": "/ɪkˈspens/"},
    "expensive": {"tr": "pahalı, masraflı", "ph": "/ɪkˈspensɪv/"},
    "experience": {"tr": "deneyim, tecrübe; tecrübe etmek", "ph": "/ɪkˈspɪəriəns/"},
    "experienced": {"tr": "deneyimli, tecrübeli", "ph": "/ɪkˈspɪəriənst/"},
    "experiment": {"tr": "deney yapmak; deney, tecrübe", "ph": "/ɪkˈsperɪmənt/"},
    "expert": {"tr": "uzman, bilirkişi, ehil", "ph": "/ˈekspɜːt/"},
    "explain": {"tr": "açıklamak, izah etmek", "ph": "/ɪkˈspleɪn/"},
    "explanation": {"tr": "açıklama, izahat, gerekçe", "ph": "/ˌekspləˈneɪʃn/"},
    "explode": {"tr": "patlamak, infilak etmek", "ph": "/ɪkˈspləʊd/"},
    "exploration": {"tr": "keşif, araştırma, inceleme", "ph": "/ˌekspləˈreɪʃn/"},
    "explore": {"tr": "keşfetmek, araştırmak, incelemek", "ph": "/ɪkˈsplɔː(r)/"},
    "explosion": {"tr": "patlama, infilak", "ph": "/ɪkˈspləʊʒn/"},
    "export": {"tr": "ihraç etmek; ihracat", "ph": "/ˈekspɔːt/"},
    "expose": {"tr": "maruz bırakmak, açığa çıkarmak, ifşa etmek", "ph": "/ɪkˈspəʊz/"},
    "express": {"tr": "ifade etmek, dile getirmek; ekspres, hızlı", "ph": "/ɪkˈspres/"},
    "expression": {"tr": "ifade, deyim, anlatım", "ph": "/ɪkˈspreʃn/"},
    "extend": {"tr": "uzatmak, genişletmek, yaymak", "ph": "/ɪkˈstend/"},
    "extent": {"tr": "boyut, derece, kapsam, sınır", "ph": "/ɪkˈstent/"},
    "external": {"tr": "harici, dış, dışsal", "ph": "/ɪkˈstɜːnl/"},
    "extra": {"tr": "ekstra, fazladan, ilave", "ph": "/ˈekstrə/"},
    "extraordinary": {"tr": "olağanüstü, fevkalade, sıra dışı", "ph": "/ɪkˈstrɔːdnri/"},
    "extreme": {"tr": "aşırı, uç, radikal", "ph": "/ɪkˈstriːm/"},
    "extremely": {"tr": "son derece, fevkalade, aşırı derecede", "ph": "/ɪkˈstriːmli/"},
    "eye": {"tr": "göz; bakmak, süzmek", "ph": "/aɪ/"}
}

print(f"Loaded {len(CURATED_DICT)} detailed words.")
